# Test Stack

name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install gcc
      run: |
        sudo apt install build-essential
    - name: Test
      run: |
        gcc stack.c 
        ./a.out
